- name: Deploy dozzle stack
  community.docker.docker_stack:
    state: present
    name: dozzle
    compose:
      - "{{ dozzle_compose }}"
    prune: true
  vars:
    dozzle_compose: "{{ lookup('template', role_path + '/templates/docker-compose.yml.j2') | from_yaml }}"
