- name: Get info on redis network
  community.docker.docker_network_info:
    name: redis
  register: redis_network

- name: Create redis network
  community.docker.docker_network:
    name: redis
    driver: overlay
    scope: swarm
    attachable: true
    appends: true
  when: not redis_network.exists

- name: Create redis password secret
  community.docker.docker_secret:
    name: redis-password
    data: "{{ lookup('ansible.builtin.password', role_path + '/files/credentials/password.txt', length=32) | b64encode }}"
    data_is_b64: true
    state: present

- name: Deploy redis stack
  community.docker.docker_stack:
    state: present
    name: redis
    compose:
      - "{{ redis_compose }}"
    prune: true
  vars:
    redis_compose: "{{ lookup('template', role_path + '/templates/docker-compose.yml.j2') | from_yaml }}"
