- name: Build custom Jellyfin image
  community.docker.docker_image_build:
    path: "{{ role_path }}/files"
    name: "{{ image }}"
    pull: true
    rebuild: "always"
    outputs:
      - push: true
        type: image

- name: Create LDAP config in Docker
  community.docker.docker_config:
    name: jellyfin_ldap_config
    data: "{{ lookup('template', role_path + '/templates/LDAP-Auth.xml.j2') | b64encode }}"
    data_is_b64: true
    state: present
    rolling_versions: true
  register: jellyfin_config

- name: Deploy jellyfin stack
  community.docker.docker_stack:
    state: present
    name: jellyfin
    compose:
      - "{{ jellyfin_compose }}"
    prune: true
  vars:
    jellyfin_compose: "{{ lookup('template', role_path + '/templates/docker-compose.yml.j2') | from_yaml }}"
