# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/schemas/main/f/ansible.json

- name: Prepare the metal for deployment
  hosts: manager
  become: true
  gather_facts: true
  roles:
    - prepare

- name: Configure Cloudflare Zero Trust
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create Cloudflare Zero Trust Tunnel
      cloudflare_tunnel:
        state: present
        api_email: "{{ lookup('ansible.builtin.env', 'CLOUDFLARE_API_EMAIL') }}"
        api_key: "{{ lookup('ansible.builtin.env', 'CLOUDFLARE_API_KEY') }}"
        account_id: "{{ lookup('ansible.builtin.env', 'CLOUDFLARE_ACCOUNT_ID') }}"
        tunnel_secret: "{{ lookup('ansible.builtin.env', 'CLOUDFLARE_TUNNEL_SECRET') }}"
        name: "homelab ({{ lookup('ansible.builtin.env', 'INSTANCE_NAME') }})"
      register: cloudflare_tunnel

- name: Deploy Docker stacks
  hosts: manager
  gather_facts: true
  pre_tasks:
    - name: Set base domain
      set_fact:
        base_domain: "{{ lookup('ansible.builtin.env', 'CLOUDFLARE_BASE_DOMAIN') }}"
  roles:
    # basic infrastructure
    - registry
    - device-mapping-manager
    - postgres
    - redis

    # remote access
    - cloudflared

    # authentication
    - openldap
    - authelia

    # general management
    - portainer
    - dozzle

    # media server
    - media-server
    - transmission
    - prowlarr
    - sonarr
    - radarr
    - recyclarr
    - jellyfin
    - jellyseerr
    - samba

    # manager
    - manager
