- name: Configure Cloudflare Zero Trust
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create Cloudflare Zero Trust Tunnel
      cloudflare_tunnel:
        state: present
        api_email: "{{ lookup('ansible.builtin.env', 'CLOUDFLARE_API_EMAIL') }}"
        api_key: "{{ lookup('ansible.builtin.env', 'CLOUDFLARE_API_KEY') }}"
        account_id: "{{ lookup('ansible.builtin.env', 'CLOUDFLARE_ACCOUNT_ID') }}"
        tunnel_secret: "{{ lookup('ansible.builtin.env', 'CLOUDFLARE_TUNNEL_SECRET') }}"
        name: homelab2
      register: cloudflare_tunnel

- name: Prepare the metal for deployment
  hosts: manager
  become: true
  gather_facts: true
  roles:
    - prepare

- name: Deploy Docker stacks
  hosts: manager
  gather_facts: true
  roles:
    - registry
    - postgres
    - redis
    - cloudflared
    - openldap
    - authelia
    - cfzt-sync
    - portainer
    - dozzle
