- name: Create configuration
  community.docker.docker_config:
    name: recyclarr-config
    data: "{{ lookup('template', role_path + '/templates/recyclarr.yml.j2') | b64encode }}"
    data_is_b64: true
    state: present
    rolling_versions: true
  register: recyclarr_config

- name: Deploy recyclarr stack
  community.docker.docker_stack:
    state: present
    name: recyclarr
    compose:
      - "{{ recyclarr_compose }}"
    prune: true
  vars:
    recyclarr_compose: "{{ lookup('template', role_path + '/templates/docker-compose.yml.j2') | from_yaml }}"
