[package]
name = "homelab-manager"
version = "0.1.0"
description = "Tool for bootstrapping and managing the homelab"
edition = "2021"
publish = false

[dependencies]
base64 = "0.22"
clap = { version = "4.5", default-features = true, features = [
  "derive",
  "cargo",
  "env",
  "wrap_help",
] }
dialoguer = "0.11"
glob = "0.3"
ignore = "0.4"
rand = { version = "0.8", default-features = false, features = [
  "std",
  "std_rng",
] }
regex = "1.10"
reqwest = { version = "0.12", default-features = false, features = [
  "http2",
  "charset",
  "blocking",
  "rustls-tls",
] }
serde = { version = "1.0", default-features = true, features = [
  "derive",
  "alloc",
] }
serde_json = "1.0"
serde_yaml = "0.9"
users = { version = "0.11", default-features = false }
uuid = { version = "1.8", features = ["v4"] }
