all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3

  children:
    workers:
      hosts:
        localhost:
    manager:
      hosts:
        localhost:
    leader:
      hosts:
        localhost:
    nonleaders:
      hosts:
        localhost:
