services:
  tunnel:
    image: cloudflare/cloudflared
    container_name: cloudflared-tunnel
    network_mode: host
    environment:
      - TUNNEL_TOKEN=${TOKEN:cloudflared}
      # We use quic to ensure DNS functionality works through Cloudflare
      - TUNNEL_TRANSPORT_PROTOCOL=quic
    restart: unless-stopped
    command: tunnel run
