- name: Create radarr api key
  ansible.builtin.set_fact:
    radarr_api_key: "{{ lookup('ansible.builtin.password', role_path + '/files/credentials/api_key.txt', length=32, chars=['ascii_letters']) }}"

- name: Create configuration
  community.docker.docker_config:
    name: radarr-config
    data: "{{ lookup('template', role_path + '/templates/config.xml.j2') | b64encode }}"
    data_is_b64: true
    state: present
    rolling_versions: true
  register: radarr_config

- name: Deploy radarr stack
  community.docker.docker_stack:
    state: present
    name: radarr
    compose:
      - "{{ radarr_compose }}"
    prune: true
  vars:
    radarr_compose: "{{ lookup('template', role_path + '/templates/docker-compose.yml.j2') | from_yaml }}"
