services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    user: "1000"
    volumes:
      - ./data:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
