- name: Build Docker image
  community.docker.docker_image_build:
    path: "{{ role_path }}/files"
    name: "{{ image }}"
    pull: true
    rebuild: "always"
    outputs:
      - push: true
        type: image

- name: Deploy manager stack
  community.docker.docker_stack:
    state: present
    name: homelab_manager
    compose:
      - "{{ manager_compose }}"
    prune: true
    resolve_image: always
  vars:
    manager_compose: "{{ lookup('template', role_path + '/templates/docker-compose.yml.j2') | from_yaml }}"
