services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    network_mode: host
    environment:
      - NGINX_PORT=80
      - PUID=${UID}
      - PGID=${GID}
      - TZ=America/Chicago
    volumes:
      - ./config:/config
      # - ./config:/etc/nginx/conf.d
      # - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
