- name: Create authelia storage encryption key secret
  community.docker.docker_secret:
    name: authelia-encryption-key
    data: "{{ lookup('ansible.builtin.password', role_path + '/files/credentials/encryption-key.txt', length=32) | b64encode }}"
    data_is_b64: true
    state: present

- name: Create authelia session secret
  community.docker.docker_secret:
    name: authelia-session-secret
    data: "{{ lookup('ansible.builtin.password', role_path + '/files/credentials/session-secret.txt', length=32) | b64encode }}"
    data_is_b64: true
    state: present

- name: Create authelia jwt secret
  community.docker.docker_secret:
    name: authelia-jwt-secret
    data: "{{ lookup('ansible.builtin.password', role_path + '/files/credentials/jwt-secret.txt', length=32) | b64encode }}"
    data_is_b64: true
    state: present

- name: Create authelia client secret
  ansible.builtin.set_fact:
    authelia_client_secret: "{{ lookup('ansible.builtin.password', role_path + '/files/credentials/client_secret.txt', length=32, chars=['ascii_letters']) }}"

- name: Create authelia client secret docker secret
  community.docker.docker_secret:
    name: authelia_client_secret
    data: "{{ authelia_client_secret | b64encode }}"
    data_is_b64: true
    state: present

- name: Generate RSA key for authelia
  community.crypto.openssl_privatekey:
    path: "{{ role_path + '/files/credentials/private_key.pem' }}"
    size: 2048
    type: RSA
  environment:
    # NOTE: i need this since otherwise the cryptography installed from the nix
    # dev env is used, which is broken for some reason. resetting this variable
    # forces python to use the cryptography package that is globally installed,
    # which should work fine.
    PYTHONPATH: ""

- name: Create configuration
  community.docker.docker_config:
    name: authelia-config
    data: "{{ lookup('template', role_path + '/templates/configuration.yml.j2') | b64encode }}"
    data_is_b64: true
    state: present
    rolling_versions: true
  register: authelia_config

- name: Deploy authelia stack
  community.docker.docker_stack:
    state: present
    name: authelia
    compose:
      - "{{ authelia_compose }}"
    prune: true
  vars:
    authelia_compose: "{{ lookup('template', role_path + '/templates/docker-compose.yml.j2') | from_yaml }}"

- name: Create Authelia IDP in Cloudflare
  cloudflare_idp:
    state: present
    api_email: "{{ lookup('ansible.builtin.env', 'CLOUDFLARE_API_EMAIL') }}"
    api_key: "{{ lookup('ansible.builtin.env', 'CLOUDFLARE_API_KEY') }}"
    account_id: "{{ lookup('ansible.builtin.env', 'CLOUDFLARE_ACCOUNT_ID') }}"
    client_secret: "{{ authelia_client_secret }}"
    name: Authelia
  register: cloudflare_idp

- name: Set Authelia IDP fact
  ansible.builtin.set_fact:
    authelia_idp_id: "{{ cloudflare_idp.idp_id }}"
