- name: Create sonarr api key
  ansible.builtin.set_fact:
    sonarr_api_key: "{{ lookup('ansible.builtin.password', role_path + '/files/credentials/api_key.txt', length=32, chars=['ascii_letters']) }}"

- name: Create configuration
  community.docker.docker_config:
    name: sonarr-config
    data: "{{ lookup('template', role_path + '/templates/config.xml.j2') | b64encode }}"
    data_is_b64: true
    state: present
    rolling_versions: true
  register: sonarr_config

- name: Deploy sonarr stack
  community.docker.docker_stack:
    state: present
    name: sonarr
    compose:
      - "{{ sonarr_compose }}"
    prune: true
  vars:
    sonarr_compose: "{{ lookup('template', role_path + '/templates/docker-compose.yml.j2') | from_yaml }}"
