- name: Deploy portainer stack
  community.docker.docker_stack:
    state: present
    name: portainer
    compose:
      - "{{ portainer_compose }}"
    prune: true
  vars:
    portainer_compose: "{{ lookup('template', role_path + '/templates/docker-compose.yml.j2') | from_yaml }}"
