networks:
  agent_network:
    driver: overlay
    attachable: true
  cloudflared-network:
    external: true

volumes:
  portainer_data:

services:
  agent:
    image: portainer/agent:2.21.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:2.21.4
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      # - "9443"
      - "9000"
      # - "8000:8000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - agent_network
      - cloudflared-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        dev.mattprovost.portainer.domain: portainer.home.mattprovost.dev
        dev.mattprovost.portainer.port: 9000
        dev.mattprovost.portainer.access: "true"
