- name: Build Docker image
  community.docker.docker_image_build:
    path: "{{ role_path }}/files"
    name: "{{ image }}"
    rebuild: "always"
    outputs:
      - push: true
        type: image

- name: Deploy cfzt-sync stack
  docker_stack:
    state: present
    name: cfzt-sync
    compose:
      - "{{ cfzt_compose }}"
    prune: true
    resolve_image: always
  vars:
    cfzt_compose: "{{ lookup('template', role_path + '/templates/docker-compose.yml.j2') | from_yaml }}"
