services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=America/Chicago
    volumes:
      - ./config:/config
    # FIXME: with network_mode: host, the port doesn't get reassigned
    # ports:
    #   - ${PORT:homeassistant}:8123 #optional
    # devices:
    #   - /path/to/device:/path/to/device #optional
    restart: unless-stopped
