- name: Deploy bitmagnet stack
  community.docker.docker_stack:
    state: present
    name: bitmagnet
    compose:
      - "{{ bitmagnet_compose }}"
    prune: true
  vars:
    bitmagnet_compose: "{{ lookup('template', role_path + '/templates/docker-compose.yml.j2') | from_yaml }}"
