- name: Get info on postgres network
  community.docker.docker_network_info:
    name: postgres
  register: postgres_network

- name: Create postgres network
  community.docker.docker_network:
    name: postgres
    driver: overlay
    scope: swarm
    attachable: true
    appends: true
  when: not postgres_network.exists

- name: Create radarr api key
  ansible.builtin.set_fact:
    postgres_password: "{{ lookup('ansible.builtin.password', role_path + '/files/credentials/password.txt', length=32) }}"

- name: Create postgres password secret
  community.docker.docker_secret:
    name: postgres-password
    data: "{{ postgres_password | b64encode }}"
    data_is_b64: true
    state: present

- name: Build Docker image
  community.docker.docker_image_build:
    path: "{{ role_path }}/files"
    name: "{{ image }}"
    rebuild: "always"
    outputs:
      - push: true
        type: image

- name: Deploy postgres stack
  community.docker.docker_stack:
    state: present
    name: postgres
    compose:
      - "{{ postgres_compose }}"
    prune: true
    resolve_image: always
  vars:
    postgres_compose: "{{ lookup('template', role_path + '/templates/docker-compose.yml.j2') | from_yaml }}"
