- name: Get info on cloudflared network
  community.docker.docker_network_info:
    name: cloudflared-network
  register: cloudflared_network

- name: Create cloudflared network
  community.docker.docker_network:
    name: cloudflared-network
    driver: overlay
    scope: swarm
    attachable: true
    appends: true
  when: not cloudflared_network.exists

- name: Deploy cloudflared stack
  community.docker.docker_stack:
    state: present
    name: cloudflared
    compose:
      - "{{ cloudflared_compose }}"
    prune: true
  vars:
    cloudflared_compose: "{{ lookup('template', role_path + '/templates/docker-compose.yml.j2') | from_yaml }}"
